### ISSUE TITLE
how to attach it to a bridge network so that Prometheus container has access to it 

### ISSUE THREAD

**Issue by durumanohar** [nginxinc/nginx-prometheus-exporter#10]
I have a nginx container running on localhost:70/nginx_status 
I have a prometheus container running on localhost:9090 

when i run 
docker run -it -p 9113:9113 --network bridge  nginx/nginx-prometheus-exporter:0.1.0  -nginx.scrape-uri http://localhost:70/nginx_status

error
Could not create Nginx Client: Failed to create NginxClient: failed to get http://localhost:70/nginx_status: Get http://localhost:70/nginx_status: dial tcp 127.0.0.1:70: connect: connection refused

docker ps -a shows that nginx-prometheus(stoic_goldberg) exited 

how do i get this container to be on the same default network(bridge) 
the connection failed error is because it does not have access to http://localhost:70/nginx_status because it is not on the same "bridge" network

**Comment by pleshakov** [comment]
@durumanohar 
by default, containers are added to the same default bridge.

in the docker run command for the exporter, you need to use the IP of the NGINX container. You can get it by looking at the output of  `docker network inspect bridge`.

Alternatively, you can create your own bridge. Please see https://docs.docker.com/network/bridge/  One of the advantages is that the exporter container can use DNS to resolve the IP of the NGINX container
