### ISSUE TITLE
Non-root container

### ISSUE THREAD

**Issue by alex1989hu** [nginxinc/nginx-prometheus-exporter#102]
**Is your feature request related to a problem? Please describe.**
Using `nginx-prometheus-exporter` in security-enhanced (like active `PodSecurityPolicy`) Kubernetes (or OpenShift) cluster requires non-root containers. It is common to use `scratch` image to reduce attack surface and get a smaller final image.

**Describe the solution you'd like**
- Non-root container - `USER` in Dockerfile
- Use `scratch` image 

**Describe alternatives you've considered**

**Additional context**
`nginx-prometheus-exporter` is written in Go, thus `alpine:3.11` is not needed to run it.

**Comment by GCHQDeveloper0985** [comment]
I'm also very interested in this change being made. Any idea over what sort of time frame we can hope to see the PR merged and released?

**Comment by lucacome** [comment]
Hi @alex1989hu thanks for the PR!

I think moving to non-root container makes sense, but I'm not sure about scratch. Alpine doesn't add much overhead to the scratch image and it's pretty secure (it's like one of their main goals) and you get a shell to attach to in case you need to debug something.

Do you have any data about images size or vulnerabilities of Alpine?

Cheers.
