### ISSUE TITLE
Strongly hope to support obtaining indicators through k8s Service name

### ISSUE THREAD

**Issue by ClementIV** [nginxinc/nginx-prometheus-exporter#105]
The output is as follows
```bash

2020/06/12 13:27:32 Starting NGINX Prometheus Exporter Version=0.7.0 GitCommit=a2910f1
2020/06/12 13:27:32 Could not create Nginx Client: failed to get http://myyyy:80/nginx_status: Get http://myyyy:80/nginx_status: dial tcp: lookup myyyy on 172.21.0.10:53: no such host

```
”myyyy“ is a service in my k8s
but it don't work！！！

**Comment by pleshakov** [comment]
Hi @ClementIV 

This error means the service DNS name couldn't be resolved by the DNS server.

I suggest taking a look at this doc https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#create-a-simple-pod-to-use-as-a-test-environment  to check that it is possible to resolve that DNS name.

**Comment by ClementIV** [comment]
@peterkellyonline  thank you very much, I will try it!
