### ISSUE TITLE
default port

### ISSUE THREAD

**Issue by ortiga88** [nginxinc/nginx-prometheus-exporter#112]
Can you change the configuration instead of port 8080 that listens on port 8888 ???

**Comment by Rulox** [comment]
Hi @ortiga88 

Are you referring to the port where NGINX exposes the `/stub_status` or NGINX Plus API metrics?

If so, when you configure the `SCRAPE_URI` env variable or `nginx.scrape-uri` cli-argument of this exporter, you can set a port there, for instance: `SCRAPE_URI=http://127.0.0.1:<YOUR_PORT>/stub_status`. We just use `8080` as default, but it can be changed with those parameters.

Let me know if this helps or you're referring to other thing.

**Comment by ortiga88** [comment]
thanks
