### ISSUE TITLE
when i start exporter ,i got this

### ISSUE THREAD

**Issue by pllsxyc** [nginxinc/nginx-prometheus-exporter#119]
# nginx-prometheus-exporter -nginx.scrape-uri http://127.0.0.1:6666/stub_status
2020/09/07 02:13:14 Starting NGINX Prometheus Exporter Version=0.8.0 GitCommit=de15093
2020/09/07 02:13:14 Could not create Nginx Client: failed to parse response body "Active connections: 1 \nserver accepts handled requests request_time\n 55 55 55 175255\nReading: 0 Writing: 1 Waiting: 0 \n": invalid input for connections and requests " 55 55 55 175255"

**Comment by Dean-Coakley** [comment]
Hi @pllsxyc 

Can you provide more details about the NGINX instance you are trying to scrape for metrics? 
* NGINX version? 
* Output of `curl http://127.0.0.1:6666/stub_status`?

My expectation is that you are running some NGINX based webserver like [tengine](https://github.com/alibaba/tengine). This exporter only supports official builds of NGINX. (From https://nginx.org/en/download.html for example)

**Comment by ClementIV** [comment]
I encountered the same problem, and the Nginx version is 1.17,
This is because there is one more indicator -> request
_time

I Will fix this bug

**Comment by pllsxyc** [comment]
sorry, the nginx version i use is tengine and i found it expose some field that the official nginx version not have，when i use the official’s nginx，the exporter working fine。


| |
彭林林
|
|
pllsxyc@163.com
|
签名由网易邮箱大师定制


On 09/7/2020 20:55，Dean Coakley<notifications@github.com> wrote：

Hi @pllsxyc

Can you provide more details about the NGINX instance you are trying to scrape for metrics?

NGINX version?
Output of curl http://127.0.0.1:6666/stub_status?

My expectation is that you are running some NGINX based webserver like tengine. This exporter only supports official builds of NGINX. (From https://nginx.org/en/download.html for example)

**Comment by Dean-Coakley** [comment]
@ClementIV `request_time` is only present in tengine stub_status. https://tengine.taobao.org/document/http_stub_status.html

This exporter does not support tengine, and is designed to only work with official builds of nginx.
You can see an example output of stub_status here: https://demo.nginx.com/stub_status
