### ISSUE TITLE
Problem with flag -nginx.ssl-ca-cert

### ISSUE THREAD

**Issue by wues4** [nginxinc/nginx-prometheus-exporter#120]
Hi,

I'm trying to run nginx_exporter with few flags and I'm still getting this message 

> flag provided but not defined: -nginx.ssl-ca-cert

here is how I run it
`/usr/local/bin/nginx_exporter -nginx.scrape-uri "https://127.0.0.1:443/status" -nginx.ssl-ca-cert "/etc/pki/tls/cert.pem"
`
I tried without quotations and get the same results.

I'm using nginx_exporter versions 0.6.0

Any ideas ?

**Comment by Dean-Coakley** [comment]
Hi @wues4 ,

That cli argument was added in `0.7.0`. I recommend updating.

**Comment by wues4** [comment]
Thank you @Dean-Coakley !
