### ISSUE TITLE
Support multiple architectures (ie arm)

### ISSUE THREAD

**Issue by David-Igou** [nginxinc/nginx-prometheus-exporter#121]
**Is your feature request related to a problem? Please describe.**

The current automated releases are only for x86 architecture. 

**Describe the solution you'd like**
Updating the current CI to build for multiple architectures (ie docker buildx)

**Comment by Dean-Coakley** [comment]
Thanks for the feature request.

This is something we'd like to support. I'll let you know when I have an update to share.

**Comment by gricuk** [comment]
Hi! Do you have a roadmap to implement arm64 architecture?

**Comment by Dean-Coakley** [comment]
I think it should be.

Confirm @nginxinc/kic?

**Comment by ogarrett** [comment]
We don't have a firm roadmap yet to extend the automated releases to create arm64 builds.  We will of course track this issue, so if anyone is interested, please let us know, thank you

**Comment by lucacome** [comment]
@David-Igou @gricuk Just letting you know that we released https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.9.0 with support for multiple architectures, in case you missed 🙂
