### ISSUE TITLE
 response: json: cannot unmarshal object into Go value of type client.versions when starting exporter

### ISSUE THREAD

**Issue by VR6Pete** [nginxinc/nginx-prometheus-exporter#14]
**Describe the bug**
error when starting the exporter I get the following error:

 response: json: cannot unmarshal object into Go value of type client.versions

**To reproduce**

Run ./nginx-prometheus-exporter -nginx.plus -nginx.scrape-uri http://localhost/status/ locally to my nginx instance.

Running nginx 1.2.2

Expected exporter to run 

**Your environment**
NGINX Plus V1.2.2

**Comment by pleshakov** [comment]
@VR6Pete could you possibly provide the output of running the following commands?

`nginx -V`
`curl http://localhost/status`

**Comment by VR6Pete** [comment]
```
ubuntu@ukasnginx03:~$ nginx -V
nginx version: nginx/1.11.10 (nginx-plus-r12-p2)
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --build=nginx-plus-r12-p2 --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_jwt_module --with-http_auth_request_module --with-http_dav_module --with-http_f4f_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_hls_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_session_log_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
```

I did a curl on the URL an it outputted loads of json - but don't really want to post that in a public place as it contains sensitive hostnames :)

**Comment by pleshakov** [comment]
@VR6Pete thanks for providing the info.

Unfortunately, the Prometheus exporter does not work with old releases of NGINX Plus. The exporter requires the version 2 of [NGINX Plus API](http://nginx.org/en/docs/http/ngx_http_api_module.html#api), which was introduced in NGINX Plus R14.

**Comment by pleshakov** [comment]
More info about transitioning from the old status API to the new API is here https://www.nginx.com/blog/transitioning-to-nginx-plus-api-configuration-monitoring/

**Comment by VR6Pete** [comment]
Ok Thanks, I had best schedule in upgrading in that case. 

Cheers.

Pete
