### ISSUE TITLE
Improve CD

### ISSUE THREAD

**Issue by M0NsTeRRR** [nginxinc/nginx-prometheus-exporter#145]
Hello,

Can you tag new release when it's needed, last release is really outdated ? (to avoid local build)
Also maybe we could improve the CI and use [goreleaser](https://github.com/goreleaser/goreleaser) to get binaries for several platforms.
It's really easy to add it, I can do it if you agree with the idea.

Best regards,

**Comment by lucacome** [comment]
Hi @M0NsTeRRR, thanks for the suggestion, we'll look into it!

Out of curiosity what platform are you using or do you think are needed?

We'll create a new release soon, stay tuned 🙂

**Comment by M0NsTeRRR** [comment]
Hey @lucacome 

I'm using an RPI sometimes for testing purpose :)

With goreleaser several platforms (all I don't remember ?) are included so it won't be important anymore.

If you want I can create a testing PR using github actions just ask !

**Comment by M0NsTeRRR** [comment]
hey @lucacome thanks for your works, can you also tag a new release ? :)

**Comment by lucacome** [comment]
@M0NsTeRRR Yep I’ll release as soon as #165 gets approved 😄

**Comment by lucacome** [comment]
The release was published @M0NsTeRRR
