### ISSUE TITLE
No -nginx.ssl-verify argument

### ISSUE THREAD

**Issue by fishhead108** [nginxinc/nginx-prometheus-exporter#15]
Hi.

**Describe the bug**
There is no argument nginx.ssl-verify

**To reproduce**
1. `docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.1.0 -nginx.scrape-uri https://site.com/basic_status`
2018/10/05 16:30:56 Starting NGINX Prometheus Exporter Version=0.1.0 GitCommit=8d90a86
2018/10/05 16:30:56 Could not create Nginx Client: Failed to create NginxClient: failed to get https://site.com/basic_status: Get https://site.com/basic_status: x509: failed to load system roots and no roots provided
2. `docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.1.0 -nginx.scrape-uri https://site.com/basic_status -nginx.ssl-verify false
`
flag provided but not defined: -nginx.ssl-verify
Usage of /usr/bin/exporter:
  -nginx.plus
        Start the exporter for NGINX Plus. By default, the exporter is started for NGINX.
  -nginx.scrape-uri string
        A URI for scraping NGINX or NGINX Plus metrics.
                For NGINX, the stub_status page must be available through the URI. For NGINX Plus -- the API. (default "http://127.0.0.1:8080/stub_status")
  -web.listen-address string
        An address to listen on for web interface and telemetry. (default ":9113")
  -web.telemetry-path string
        A path under which to expose metrics. (default "/metrics")

**Comment by pleshakov** [comment]
@fishhead108 
the code to support the `-nginx.ssl-verify` flag https://github.com/nginxinc/nginx-prometheus-exporter/commit/90107cb5bb2bada1541019cdb74468b36ad6a08f was merged into the master branch. However, that code haven't made into a new release yet. 
We're planning to release a new version (0.2) that will include that flag later this month.

**Comment by Eckelf** [comment]
Any news on this? @pleshakov

**Comment by pleshakov** [comment]
@Eckelf unfortunately, we weren't able to publish the 0.2 release by the end of October. our new target is the beginning of the next week. 

As a workaround, please build the container image or  the binaries using the following instructions -- https://github.com/nginxinc/nginx-prometheus-exporter#building-the-exporter

**Comment by pleshakov** [comment]
Release 0.2.0 that includes `-nginx.ssl-verify` is now available. Please see https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.2.0
