### ISSUE TITLE
-web.listen-address not changing listen address

### ISSUE THREAD

**Issue by matejzero** [nginxinc/nginx-prometheus-exporter#153]
**Describe the bug**

When using -web.listen-address parameter, exporter won't listen on another port / host:port.

**To reproduce**

I used the latest binary and also manually compiled the latest version, but the problem persist.

In case I already have an exporter running:
```
./nginx-prometheus-exporter  -nginx.ssl-verify false -web.listen-address ":9125"
2021/02/25 11:36:56 Starting NGINX Prometheus Exporter Version= GitCommit=
2021/02/25 11:36:56 Could not create listener: listen tcp :9113: bind: address already in use
```

No exporter running:
```
./nginx-prometheus-exporter  -nginx.ssl-verify false -web.listen-address ":9125"
2021/02/25 11:38:38 Starting NGINX Prometheus Exporter Version= GitCommit=
2021/02/25 11:38:38 Listening on :9113
2021/02/25 11:38:38 NGINX Prometheus Exporter has successfully started
```

**Expected behavior**

I expected exporter to bind to port 9125.

**Your environment**

Exporter version 0.8.0 or latest commit (0347e7678a1f5b824a2978745466bccba64a3899).

**Comment by pleshakov** [comment]
Hi @matejzero 

For `-nginx.ssl-verify false`, it is necessary to use `-nginx.ssl-verify=false` . This is due to the go built in flag library -- https://golang.org/pkg/flag/#hdr-Command_line_flag_syntax

**Comment by matejzero** [comment]
That fixed it! Would have never find that solution myself.

It would be good to add that to help(-h) output. It might help others who are not aware of this special case.

Thanks for the hint.
