### ISSUE TITLE
failed to run the exporter on Mac Big Sur

### ISSUE THREAD

**Issue by viktoryi** [nginxinc/nginx-prometheus-exporter#178]
**Is your feature request related to a problem? Please describe.**
I could run the exporter on CentOS, but I failed to run it on Mac(os: big sur, version: 11.2.3). I got below message when I tried to execute it. Does this exporter support the Mac OS platform.

```
zsh: exec format error: ./nginx-prometheus-exporter
```

**Comment by lucacome** [comment]
Hi @viktoryi 

We don't provide binaries for macOS at the moment, but if it's something that people are interested in, we can add it as a platform. 

You can still build the exporter locally on macOS with `make nginx-prometheus-exporter`, let me know if that works.

**Comment by brianehlert** [comment]
Checking in to see if the suggestion was helpful / useful.
