### ISSUE TITLE
can't build binary on Centos7

### ISSUE THREAD

**Issue by jungle-ai** [nginxinc/nginx-prometheus-exporter#193]
Environment:
CentOS Linux release 7.9.2009 (Core)
[bx@bx nginx-prometheus-exporter]$ make -v
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[bx@bx nginx-prometheus-exporter]$ go version
go version go1.15.5 linux/amd64

[bx@bx nginx-prometheus-exporter]$ make
CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -X main.version=0.9.0 -X main.commit=b07f18b5ced7a2f8bc6a5c79c519ebbd34d40885 -X main.date=2021-05-22T08:59:00Z" -o nginx-prometheus-exporter
go: github.com/golangci/golangci-lint@v1.40.1 requires
        github.com/sonatard/noctx@v0.0.1 requires
        golang.org/x/tools@v0.0.0-20200117220505-0cba7a3a9ee9 requires
        golang.org/x/mod@v0.1.1-0.20191105210325-c90efee705ee: invalid version: git fetch --unshallow -f origin in /home/centos/go/pkg/mod/cache/vcs/13df7481b5cc3358460b717a6142fe8dbaae7652e5d05689849f419ffd40ac12: exit status 128:
        fatal: git fetch-pack: expected shallow list
make: *** [nginx-prometheus-exporter] Error 1

**Comment by lucacome** [comment]
Hi @jungle-ai 

we're currently using go `1.16`, if you're using an older version of go you would need to set `GO111MODULE=on`.

You can always download the binary for the latest version from the release page https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.9.0

Let me know if it helps.

**Comment by brianehlert** [comment]
Checking in to see if the suggestion was helpful.
