### ISSUE TITLE
Error when defining scrape uri

### ISSUE THREAD

**Issue by r4j4h** [nginxinc/nginx-prometheus-exporter#2]
When running

the README states

`http://127.0.0.1:8080/stub_status` is the default scrape URI. Running it without changing it seems to confirm.

```
2018/08/11 00:12:14 Could not create Nginx Client: Failed to create NginxClient: failed to get http://127.0.0.1:8080/stub_status: Get http://127.0.0.1:8080/stub_status: dial tcp 127.0.0.1:8080: connect: connection refused
```

However, if I try to define it as that via `-nginx.scrape-uri="http://127.0.0.1:8080/stub_status"`, when I run it I get:

```
2018/08/11 00:11:20 Could not create Nginx Client: Failed to create NginxClient: failed to get "http://127.0.0.1:8080/stub_status": parse "http://127.0.0.1:8080/stub_status": first path segment in URL cannot contain colon
```

**Comment by Dean-Coakley** [comment]
Hi @r4j4h 

I've been unable to recreate this issue. Can you give me some more details about how exactly you are running this? 
* Did you build the image locally, or did you pull the image from our docker registry?
* What is the full command you are using to run the container?
* Docker version?

Issue appears to be that the flag is adding a set of quotes to the url. Perhaps try the alternate go flag syntax?:
`$ docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.1.0 -nginx.scrape-uri http://127.0.0.1:8080/stub_status`

**Comment by r4j4h** [comment]
Hi there,

You were right, it was with quotations.

FWIW though, I am running this in a Kubernetes Pod as a sidecar to an nginxinc nginx Ingress exporter.

Using the alternate syntax didn't seem to work:
```
  nginx-prometheus-exporter:
    Container ID:  docker://0136d7700ccaf9099029f6a4f9e3ca5d5b9600f68331893b402b0295211a8f29
    Image:         nginx/nginx-prometheus-exporter:0.1.0
    Image ID:      docker-pullable://nginx/nginx-prometheus-exporter@sha256:24e87a3a18fd27c39e8d4fb11147ab080a0c39a3171d85e6c17954fbf09644fc
    Port:          9113/TCP
    Host Port:     9113/TCP
    Args:
      -nginx.scrape-uri http://127.0.0.1:80/stub_status
```

gives

```
flag provided but not defined: -nginx.scrape-uri http://127.0.0.1:80/stub_status
Usage of /usr/bin/exporter:
  -nginx.plus
    	Start the exporter for NGINX Plus. By default, the exporter is started for NGINX.
  -nginx.scrape-uri string
    	A URI for scraping NGINX or NGINX Plus metrics.
    		For NGINX, the stub_status page must be available through the URI. For NGINX Plus -- the API. (default "http://127.0.0.1:8080/stub_status")
  -web.listen-address string
    	An address to listen on for web interface and telemetry. (default ":9113")
  -web.telemetry-path string
    	A path under which to expose metrics. (default "/metrics")
```

But 

```
    Args:
      -nginx.scrape-uri=http://127.0.0.1:80/stub_status
```

indeed works!

Versus my prior

```
    Args:
      -nginx.scrape-uri="http://127.0.0.1:80/stub_status"
```

Thanks!

**Comment by Dean-Coakley** [comment]
Glad I could help! 

Thanks for all this extra detail. I'll take some steps to investigate if we can make this less error prone

**Comment by jgourmelen** [comment]
https://github.com/knyar/nginx-lua-prometheus/issues/108
