### ISSUE TITLE
Change interval for scraping metrics

### ISSUE THREAD

**Issue by maxence974** [nginxinc/nginx-prometheus-exporter#203]
Hi, thanks for your project.

I can't change interval between two scraping metrics from NGINX Exporter to NGINX instance.
currently, there is 30 seconds for this interval and i wish increase it.

Can you add a variable for this interval please ?

Thanks in advance.

Maxence.

**Comment by pleshakov** [comment]
Hi @maxence974 

The NGINX exporter scrapes the metric from NGINX every time it gets a request from Prometheus via `/metrics` endpoint.  

I wonder what the issue you're trying to address is? also,  could customizing the scrape interval in Prometheus configuration work for you?

**Comment by maxence974** [comment]
Hi @pleshakov , thanks for your response !
I'm sorry, i think there is an interval for prometheus AND an interval for exporter ! 

I close this issue ! have fun and thanks for projects !
