### ISSUE TITLE
Feature Request Upstream Count Up / Down

### ISSUE THREAD

**Issue by RedPepper** [nginxinc/nginx-prometheus-exporter#21]
We are already using your exporter but unfortunately there is one thing we are missing to migrate from our zabbix based nginx plus monitoring to grafana / prometheus. We need somehow the number of upstreams that have been discovered and those who are up and down. 

As my knowlege of the Go Language is limited i cannot contribute it myself.

Regards,

Mike

**Comment by pleshakov** [comment]
@RedPepper 
You can get the number of upstream servers through the following Prometheus query:
```
count(nginxplus_upstream_server_state)
```

Those which are up (in the "up" or "draining" state):
```
count(nginxplus_upstream_server_state < 3) by (upstream, server)
```

Those which are down (in the "down",  "unavail", "checking" or "unhealthy" state):
```
count(nginxplus_upstream_server_state > 2) by (upstream, server)
```

Let me know if this helps

**Comment by RedPepper** [comment]
looks like it does the trick for me just altered the query a bit to filter
