### ISSUE TITLE
Add metrics from NGINX Plus API version 7

### ISSUE THREAD

**Issue by byoda** [nginxinc/nginx-prometheus-exporter#220]
The `codes` data in responses for each HTTP [upstream](https://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_http_upstream), [server zone](https://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_http_server_zone), and [location zone](https://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_http_location_zone) were added in [version](https://nginx.org/en/docs/http/ngx_http_api_module.html#api_version) 7.

Announcement:

I am pleased to announce the release of [ **NGINX Plus R25** ](https://www.nginx.com/blog/nginx-plus-r25-released/). This release significantly extends the enterprise use cases that differentiates NGINX Plus from the open source version, namely user authentication/identity and observability. The headlines:

- Metrics API has counters per HTTP status code for monitoring backends and what gets sent to clients. Previously counters were only per HTTP class (e.g. 2xx, 4xx).

Congratulations to everyone involved in the release!

Read the full announcement at [https://www.nginx.com/blog/nginx-plus-r25-released/](https://www.nginx.com/blog/nginx-plus-r25-released/)

**Comment by brianehlert** [comment]
Comment added by Brian Ehlert in Aha! - [View](https://nginx.aha.io/comments/7076580326181839157)

I was reading through the Prometheus exporter and I think this might already be supported. Someone would need to verify. Please.

**Comment by lucacome** [comment]
We need https://github.com/nginxinc/nginx-plus-go-client/issues/106
