### ISSUE TITLE
Metrics was collected before with the same name and label values

### ISSUE THREAD

**Issue by shovelend** [nginxinc/nginx-prometheus-exporter#23]
**Describe the bug**
When running the docker container locally pointing it against our nginx lb api endpoint exposed on port `8888` I can see that errors have occurred when gathering the metrics:

```
An error has occurred during metrics gathering:
490 error(s) occurred:
* collected metric nginxplus_upstream_server_state label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > gauge:<value:3 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_active label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > gauge:<value:0 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_requests label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > counter:<value:0 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_responses label:<name:"code" value:"1xx" > label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > counter:<value:0 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_responses label:<name:"code" value:"2xx" > label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > counter:<value:0 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_responses label:<name:"code" value:"3xx" > label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > counter:<value:0 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_responses label:<name:"code" value:"4xx" > label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > counter:<value:0 >  was collected before with the same name and label values
* collected metric nginxplus_upstream_server_responses label:<name:"code" value:"5xx" > label:<name:"server" value:"127.0.0.1:80" > label:<name:"upstream" value:"gru_location_red" > counter:<value:0 >  was collected before with the same name and label values
...
...
...
And the list goes on and on.
```
Our Prometheus can't gather the metrics because of these errors. 

**To reproduce**
1. Deploy using `docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.1.0 -nginx.plus -nginx.scrape-uri http://**lb_address**:8888/api`
2. View http://localhost:9113/metrics
3. Observe the errors

**Expected behavior**
Metrics should be gathered successfully, allowing us and prometheus to pick these up.
If it's something we're doing wrong from the lb side it should be mentioned.

**Your environment**
* Version of the Prometheus exporter - `0.1.0`
* Version of Docker/Kubernetes - `Docker version 18.06.1-ce, build e68fc7a`
* [if applicable] Kubernetes platform (e.g. Mini-kube or GCP)
* Using NGINX or NGINX Plus - NGINX Plus

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by pleshakov** [comment]
@shovelend 
it looks like you have the same upstream server defined multiple times in one upstream. For example, 
```nginx
upstream test {
    zone test 64k;

    server 127.0.0.1:9093;
    server 127.0.0.1:9093;
    server 127.0.0.1:9093;
}
```

Is it the case? Is it intentional?

**Comment by shovelend** [comment]
@pleshakov You are absolutely correct! We'll make some changes today to remove duplicate definitions and get back to you after. Thanks a lot!

**Comment by shovelend** [comment]
@pleshakov removing duplicate upstream servers resolved our problems. Closing the issue.

**Comment by Goodluckhf** [comment]
> intentional

I've faced with the same problem but I did it on purpose. I have to proxy request to external LB thats why I need retries.
