### ISSUE TITLE
 how to initialize via docker using localhost

### ISSUE THREAD

**Issue by viniciuscps** [nginxinc/nginx-prometheus-exporter#25]
Hello,

Could you help me with the problem in using docker for EC2 (AWS) instances?
It happens that since I have instances configured in auto-scalling, for me it is much easier if the initialization string accepts something like localhost and / or 127.0.0.1.
But when I try to boot using them the following failures occur:

**docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.2.0**
2018/12/05 20:24:51 Starting NGINX Prometheus Exporter Version=0.2.0 GitCommit=ad0a472
2018/12/05 20:24:51 Could not create Nginx Client: Failed to create NginxClient: failed to get http://127.0.0.1:8080/stub_status: Get http://127.0.0.1:8080/stub_status: dial tcp 127.0.0.1:8080: connect: connection refused

OR 

docker run  -it -p 9113:9113 nginx/nginx-prometheus-exporter:0.2.0 -nginx.scrape-uri http://127.0.0.1:8080/stub_status
2018/12/05 20:32:15 Starting NGINX Prometheus Exporter Version=0.2.0 GitCommit=ad0a472
2018/12/05 20:32:15 Could not create Nginx Client: Failed to create NginxClient: failed to get http://127.0.0.1:8080/stub_status: Get http://127.0.0.1:8080/stub_status: dial tcp 127.0.0.1:8080: connect: connection refused

It only works if I put the external ip of the server, but how would it be automated?

Thank you in advance.

**Comment by Dean-Coakley** [comment]
Hi @viniciuscps 

My expectation is that you are deploying Nginx outside of docker. If this is the case Nginx is exposing `stub_status` on the host network interface while the exporter is checking localhost of the `docker0` bridge.

The following command binds the container directly to the Docker host’s network, with no network isolation.
`docker run -it --network host nginx/nginx-prometheus-exporter:0.2.0 -nginx.scrape-uri http://127.0.0.1:8080/stub_status`

**Comment by viniciuscps** [comment]
I would like to thank you for the help!
You're right the Nginx I boot is external to the docker and so I could not find it.

Actually I managed to initialize but I have 2 "problems":
**1- Can I go past door 9113: 9113 so he can expose the metrics? (where do I consult the generated metrics)?**
That is not works :(
docker run -it 9113:9113 --network host nginx/nginx-prometheus-exporter:0.2.0 -nginx.scrape-uri http://127.0.0.1:8080/stub_status

**2- It "holds" the screen as below, how do I start it and give me back bash !?**
[root@ip-10-0-0-177 ~]# docker run -it --network host nginx/nginx-prometheus-exporter:0.2.0 -nginx.scrape-uri http://127.0.0.1:8080/stub_status
Unable to find image 'nginx/nginx-prometheus-exporter:0.2.0' locally
0.2.0: Pulling from nginx/nginx-prometheus-exporter
8e3ba11ec2a2: Pull complete
9f154ece3361: Pull complete
Digest: sha256:3a3f7cbadb54bf47f68b57a35eaab3e62b236fa598a0f0d5eaf153483816daf3
Status: Downloaded newer image for nginx/nginx-prometheus-exporter:0.2.0

**2018/12/06 17:22:39 Starting NGINX Prometheus Exporter Version=0.2.0 GitCommit=ad0a472**
2- It "holds" the screen as below, how do I start it and give me back bash !?

[root@ip-10-0-0-177 ~]# docker ps -a
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                     PORTS               NAMES
3eb35b4fd726        nginx/nginx-prometheus-exporter:0.2.0   "/usr/bin/exporter -…"   5 minutes ago       Exited (2) 3 seconds ago                       sad_chandrasekhar


TKS a lot!

**Comment by Dean-Coakley** [comment]
1. Metrics should now be available at `localhost:9113/metrics`

2. Just run the same command in detached mode. (`-d` instead of `-it`)
`docker run -d --network host nginx/nginx-prometheus-exporter:0.2.0 -nginx.scrape-uri http://127.0.0.1:8080/stub_status`

**Comment by viniciuscps** [comment]
Dean,

I would like to thank you for your promptness and for all your help!
I was able to upload and now I am collecting the metrics correctly !!!

Thank you very much!!!

**Comment by Dean-Coakley** [comment]
Glad to help!
