### ISSUE TITLE
 Error getting stats: failed to get stats: failed to get slabs: error unmarshaling response 

### ISSUE THREAD

**Issue by rudovich** [nginxinc/nginx-prometheus-exporter#256]
Hi there,

we are faced with issue on nginx-plus powered servers (Ubuntu20) with version r26 on with the following errors:

`2022/04/18 12:51:40 Error getting stats: failed to get stats: failed to get slabs: error unmarshaling response "{\"SSL\":{\"pages\":{\"used\":6,\"free\":2538},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"64\":{\"used\":1,\"free\":63,\"reqs\":1,\"fails\":0},\"128\":{\"used\":43,\"free\":21,\"reqs\":1094,\"fails\":0},\"256\":{\"used\":42,\"free\":6,\"reqs\":1093,\"fails\":0},\"512\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"jwk\":{\"pages\":{\"used\":2,\"free\":13},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":1,\"free\":126,\"reqs\":1,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":2,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"oidc_id_tokens\":{\"pages\":{\"used\":4,\"free\":2540},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":1,\"free\":126,\"reqs\":4,\"fails\":0},\"64\":{\"used\":1,\"free\":63,\"reqs\":1,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":2,\"free\":14,\"reqs\":5,\"fails\":0},\"512\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":1,\"free\":1,\"reqs\":5,\"fails\":0}}},\"refresh_tokens\":{\"pages\":{\"used\":7,\"free\":2537},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":4,\"free\":123,\"reqs\":5,\"fails\":0},\"64\":{\"used\":1,\"free\":63,\"reqs\":1,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":5,\"free\":11,\"reqs\":6,\"fails\":0},\"512\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"oidc_pkce\":{\"pages\":{\"used\":2,\"free\":29},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":1,\"free\":126,\"reqs\":1,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":1,\"free\":15,\"reqs\":1,\"fails\":0},\"512\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"wallarm_stat\":{\"pages\":{\"used\":2,\"free\":1},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"ams_cache\":{\"pages\":{\"used\":4,\"free\":1268},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":1,\"free\":126,\"reqs\":1,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":17,\"free\":15,\"reqs\":69,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"ams\":{\"pages\":{\"used\":7,\"free\":8},\"slots\":{\"8\":{\"used\":2,\"free\":502,\"reqs\":2,\"fails\":0},\"16\":{\"used\":2,\"free\":252,\"reqs\":2,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"confluence\":{\"pages\":{\"used\":6,\"free\":9},\"slots\":{\"8\":{\"used\":1,\"free\":503,\"reqs\":1,\"fails\":0},\"16\":{\"used\":3,\"free\":251,\"reqs\":3,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"jira\":{\"pages\":{\"used\":6,\"free\":9},\"slots\":{\"8\":{\"used\":2,\"free\":502,\"reqs\":2,\"fails\":0},\"16\":{\"used\":2,\"free\":252,\"reqs\":2,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"learning\":{\"pages\":{\"used\":6,\"free\":9},\"slots\":{\"8\":{\"used\":2,\"free\":502,\"reqs\":2,\"fails\":0},\"16\":{\"used\":2,\"free\":252,\"reqs\":2,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"wgfitness\":{\"pages\":{\"used\":6,\"free\":9},\"slots\":{\"8\":{\"used\":1,\"free\":503,\"reqs\":1,\"fails\":0},\"16\":{\"used\":3,\"free\":251,\"reqs\":3,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"wgjira\":{\"pages\":{\"used\":6,\"free\":9},\"slots\":{\"8\":{\"used\":2,\"free\":502,\"reqs\":2,\"fails\":0},\"16\":{\"used\":2,\"free\":252,\"reqs\":2,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"wgra\":{\"pages\":{\"used\":7,\"free\":8},\"slots\":{\"8\":{\"used\":2,\"free\":502,\"reqs\":2,\"fails\":0},\"16\":{\"used\":2,\"free\":252,\"reqs\":2,\"fails\":0},\"32\":{\"used\":2,\"free\":125,\"reqs\":2,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":4,\"free\":28,\"reqs\":4,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":1,\"free\":7,\"reqs\":1,\"fails\":0},\"1024\":{\"used\":1,\"free\":3,\"reqs\":1,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}},\"wallarm_stat_split\":{\"pages\":{\"used\":0,\"free\":477},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":3},\"16\":{\"used\":80,\"free\":813014871,\"reqs\":17,\"fails\":138},\"32\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":225885940,\"fails\":80},\"128\":{\"used\":22,\"free\":-23,\"reqs\":0,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":0,\"free\":7879190,\"reqs\":24,\"fails\":11},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":14371663,\"fails\":0}}},\"wallarm_worker\":{\"pages\":{\"used\":9,\"free\":6},\"slots\":{\"8\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"16\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"32\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"64\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"128\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"256\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"512\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"1024\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0},\"2048\":{\"used\":0,\"free\":0,\"reqs\":0,\"fails\":0}}}}": json: cannot unmarshal number -23 into Go struct field Slot.Slots.Free of type uint64`

`nginx version: nginx/1.21.5 (nginx-plus-r26)
built by gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --build=nginx-plus-r26 --with-http_auth_jwt_module --with-http_f4f_module --with-http_hls_module --with-http_session_log_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-plus-1.21.5/debian/debuild-base/nginx-plus-1.21.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
`

`NGINX Prometheus Exporter version=0.10.0 commit=7a03d0314425793cf4001f0d9b0b2cfd19563433 date=2021-12-21T19:24:34Z`

**Comment by lucacome** [comment]
Hi @rudovich 

Can you give us some more context on when this error is happening? Some steps to reproduce maybe?

Thanks

**Comment by rudovich** [comment]
Hi!

This error begins after update exporter to version 0.10.0 and nginx-plus to 1.21
