### ISSUE TITLE
Export nginx[plus]_up metric

### ISSUE THREAD

**Issue by valibud** [nginxinc/nginx-prometheus-exporter#26]
**Is your feature request related to a problem? Please describe.**
I wouldn't call it a problem, but there is no `_up` metric exported.

**Describe the solution you'd like**
I would like to have `_up` metric exported so it's easier to write an alert that NGINX is down.

**Describe alternatives you've considered**
None yet.

**Additional context**
Maybe there is another way to write the above alert with the data that's already exported but I am not aware of it yet.

Thank you.

**Comment by oliveiraVG** [comment]
@pleshakov 

Do you have a ETA of a new relase?

**Comment by pleshakov** [comment]
@oliveiraVG yes, we'll publish it by Friday this week

**Comment by pleshakov** [comment]
the feature is available in 0.3 https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.3.0
