### ISSUE TITLE
A few development ideas

### ISSUE THREAD

**Issue by kworr** [nginxinc/nginx-prometheus-exporter#28]
Hello.

Just took a quick look on it and deployed over my hosts. There's a few things that might add to the value:

1. It would be nice to have _build_info. Currently I can't get exporter info on the board to plan tiered upgrades.

1. It would be nice to be able to scrape multiple hosts. With HTTPS/Auth nginx is already an external service that can be used to transfer data. This will also make it possible to transport data securely over network. For example, if I have a few hosts in different DCs I need to proxy exporter via nginx for example, if exporter would support scraping more then one host, authorization and HTTPS it would be possible to expose /stub_status on nginx externally in a restricted location. This will make provisioning easier.

**Comment by pleshakov** [comment]
@kworr thanks for you suggestions!

Regarding No. 1 - makes sense.

Regarding No. 2 - I'm not sure I fully understand the benefits of scraping multiple hosts at once from your example.

**Comment by pleshakov** [comment]
@kworr thanks for further clarifying your case. 

scrapping all the hosts in one exporter will complicate the implementation and configuration of the exporter. Additionally, such an exporter will present a single point of failure -- if it fails, the Prometheus will not be able to scrap the metrics of all the NGINXes.

**Comment by pleshakov** [comment]
@kworr  the nginxexporter_build_info metric has been implemented in #32.  For now, until a new release is published, to use the metric, please build your own binary or image with the exporter.

**Comment by kworr** [comment]
Thank you!

**Comment by pleshakov** [comment]
nginxexporter_build_info metric is available in 0.3 https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.3.0
