### ISSUE TITLE
exporter exits when prometheus process is reloaded

### ISSUE THREAD

**Issue by kworr** [nginxinc/nginx-prometheus-exporter#29]
Hello.

I was playing with different exporters and noticed that this exporter is quitting when I'm `pkill -1 prometheus` to renew configuration. It's not dying, I see no cores or messages about that, it just exits when connection from prometheus is closed.

**Comment by pleshakov** [comment]
@kworr the exporter process is independent from the prometheus itself and reloading prometheus configuration should not affect it.  Note that `pkill -1 prometheus` will also kill the exporter process if it is running as `nginx-prometheus-exporter` binary on that host.

**Comment by kworr** [comment]
True. Maybe it's just would be enough to create minimal signal handler so that it wouldn't die on SIGHUP? SIGHUP is generally used to force update in the running process, not to close it.

**Comment by pleshakov** [comment]
I don't think it is necessary to support it unless we use that signal for something like changing the configuration
