### ISSUE TITLE
Will there be support for this plugin for Graviton based instances

### ISSUE THREAD

**Issue by awsproserve** [nginxinc/nginx-prometheus-exporter#309]
**Is your feature request related to a problem? Please describe.**

Hi I am an engagement manager with AWS Professional services and wanting to know if there will be support for Graviton. x86 is supported, wanting to see for our customer if Graviton based instances will be supported or is it on the road map. We need to export metrics from Nginx to Prometheus. 

**Describe the solution you'd like**

Support for Graviton instances

**Describe alternatives you've considered**

We would built it ourselves but want to know whats the roadmap so we won't have to do duplicate efforts

**Additional context**
Add any other context about the feature request here.

**Comment by brianehlert** [comment]
It is about having the container image built using a compatible architecture.
The readme covers a method to build yourself.

According to:  https://github.com/aws/aws-graviton-getting-started/blob/main/containers.md
_The first step for leveraging the benefits of Graviton-based instances as container hosts is to ensure all production software dependencies support the arm64 architecture_

According to https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.11.0
arm64 is already covered.
