### ISSUE TITLE
nginx-prometheus-exporter startup failure

### ISSUE THREAD

**Issue by Chwei-L** [nginxinc/nginx-prometheus-exporter#314]
commond:  
` ./nginx-prometheus-exporter -nginx.ssl-verify=false  -nginx.scrape-uri=https://172.16.128.203:3000/nginx_status`
output:
 "022/11/04 14:14:18 Could not create Nginx Client: failed to parse response body "Active connections:  2 \nserver accepts handled requests request_time\n 60 60 240 19259\nReading: 0 Writing: 1 Waiting: 1 \n":  failed to scan template metrics: newline in format does not match input"

![120d36533539a283672adedaa6f1b09](https://user-images.githubusercontent.com/53077547/199962757-bfefbdb6-a4e7-4bd8-bc27-d1aa64ba84f7.png)

![8ab66b8ca43a47ded67f9e65de10f3d](https://user-images.githubusercontent.com/53077547/199962703-b86a9720-2ca6-428c-b277-fee3592a2a28.png)

**Comment by vepatel** [comment]
Hi @Chwei-L nginx-prometheus-exporter requires metrics to be exposed at `/stub_status` for OSS and `/api `for Plus as mentioned at https://github.com/nginxinc/nginx-prometheus-exporter#prerequisites
next when you use binary, those URIs are required for `-nginx.scrape-uri` argument, see https://github.com/nginxinc/nginx-prometheus-exporter#running-the-exporter-binary
