### ISSUE TITLE
Feature Request: Infinite retries and no sudden death on /stub_status /api timeout

### ISSUE THREAD

**Issue by devminded** [nginxinc/nginx-prometheus-exporter#336]
**Is your feature request related to a problem? Please describe.**
When running the exporter as a docker sidecar (with nomad) the (re)start order if tasks is unknown. Once the number of retries is hit, the entire pod/task-group gets re-allocated. It is also not documented that the default value is 0 and that the process will exit with code 1.

**Describe the solution you'd like**
The number of retries shall be able to set to infinite `-nginx.retries=-1` or `-nginx.noretries`. The exporter (and therefore the entire pod) shall never stop on something simple like a temporary network issue due to something like nginx config is in the process of being updated (consul template/SIGHUP). We have health checks for that purpose.

**Describe alternatives you've considered**

1. Setting the `-nginx.retries` to -1 (error) and MAX_INT (bad form).
2. Using some kind of supervisor wrapper around the exporter

**Additional context**
(Nomad job)
```
job "frontend" {
  datacenters = ["dc1"]
  type = "service"

  group "webserver" {
    count = 3

    network {
      port "http" {
        to = 80
      }
      port "metrics" {
        to = 9113
      }
    }

    service {
      name = "webserver"
      port = "http"
      tags = ["http", "environment=env1"]
      provider = "nomad"
    }

    service {
      name = "webserver-metrics"
      port = "metrics"
      tags = ["metrics", "prometheus", "environment=env1", "metrics-path=/metrics"]
      provider = "nomad"
    }

    task "nginx" {
      driver = "docker"
      config {
        image = "nginx:latest"
        ports = ["http"]
      }

      resources {
        cpu = 500
        memory = 256
      }
    }

    task "nginx-exporter" {
      driver = "docker"
      config {
        image = "nginx/nginx-prometheus-exporter:latest"
        ports = ["metrics"]
        args = ["-nginx.retries", "-1"]
      }
    }

  }
}
```

**Comment by lucacome** [comment]
@devminded I opened #504 that removes the entire retry logic and doesn't kill the exporter if nginx is not available. Do you think that would work for you?
