### ISSUE TITLE
nginx开启auth_basic "Restricted"身份认证功能  使用nginx-prometheus-exporter有没有相关参数连接

### ISSUE THREAD

**Issue by 15212577946** [nginxinc/nginx-prometheus-exporter#425]
nginx开启auth_basic "Restricted"身份认证功能  使用nginx-prometheus-exporter有没有相关参数连接

以下是我连接之后的错误
2023/06/02 06:21:32 Starting NGINX Prometheus Exporter Version= GitCommit=
2023/06/02 06:21:32 Could not create Nginx Client: expected 200 response, got 401

**Comment by brianehlert** [comment]
Any details would be helpful and useful.
deployment files, settings, etc.

Are you trying to connect to the exporter using basic auth?

**Comment by 15212577946** [comment]
> 任何细节都会有所帮助和有用。部署文件、设置等
> 
> 您是否正在尝试使用基本身份验证连接到导出器？

我使用的是docker run -it -d -p 9113:9113 --name nginx-exporter nginx/nginx-prometheus-exporter:0.8.0 -nginx.scrape-uri http://10.10.220.145/nginx_status 命令   因为我的nginx开启了auth_basic “Restricted”  访问nginx页面需要输入账号密码  所以报错了 我这边看官方文档没有关于nginx的身份认证参数

**Comment by lucacome** [comment]
Hi @15212577946 

we don't support basic auth yet. It will be available once we merge #231
