### ISSUE TITLE
Support prometheus labels for metrics

### ISSUE THREAD

**Issue by jradtilbrook** [nginxinc/nginx-prometheus-exporter#44]
**Is your feature request related to a problem? Please describe.**
I want to monitor multiple nginx instances across a fleet of services with the same prometheus instance. This doesn't work well since each instance of this exporter uses the same metric names and will clobber each other. I'd like to add support for labels in the metric so we can annotate the name of the service to support grouping by those.  
I'm a novice prometheus user so let me know if this is already somehow possible.

**Describe the solution you'd like**
Allow the exported metrics to have labels. Eg: `nginx_connections_handled{name="app1"} 2918`

**Describe alternatives you've considered**
I cannot think of another way. Is it possible to change the name or prefix the exported metrics? That would work as well but I think labels are probably nicer.

**Additional context**
N/A

**Comment by pleshakov** [comment]
@jradtilbrook 
you can add labels to your targets in the Prometheus configuration. Here is an example 
 -- https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-the-sample-targets
Can this work for you?

**Comment by jradtilbrook** [comment]
Thank you! Yes that will work. :pray: Sorry for the silly question

**Comment by pleshakov** [comment]
no problem!
