### ISSUE TITLE
New behavior of NGINX Plus r18  API module breaks prometheus

### ISSUE THREAD

**Issue by eepifanova** [nginxinc/nginx-prometheus-exporter#45]
Since NGINX Plus R18 the API module provides the list of fields according to the configuration instead of using the static list of fields.

In previous versions, the api returned the static list of fields: "nginx","processes","connections","slabs","http","stream","ssl"

Since r18, this list can be different for diffrent configurations. For example, if there are no configured stream{}, then the list of fields will be:
"nginx","processes","connections","slabs","http""ssl"

**To reproduce**
1. Upgrade NGINX Plus up to the latest r18 release
2. Comment out the whole stream {} configuration
3. See error

**Expected behavior**
The prometheus exporter should request /api/ first, to get the number of  latest available API version. After that, request /api/<VERSION> to get the list of configured fields.

**Comment by pleshakov** [comment]
@eepifanova thanks for reporting.

Until we fix the bug, there is a workaround --  putting an empty stream block in the NGINX Plus config:
```nginx
stream { }
```
