### ISSUE TITLE
Is it possible to add several parameters -nginx.scrape-uri?

### ISSUE THREAD

**Issue by drno-reg** [nginxinc/nginx-prometheus-exporter#46]
Hello,

on one node_exporter can add several parameters -nginx.scrape-uri?

for example

-nginx.scrape-uri http://localhost:8081/nginx_status http://localhost:8082/nginx_status

**Comment by pleshakov** [comment]
Hi @drno-reg 

it is not possible - the exporter only supports a single NGINX endpoint.
