### ISSUE TITLE
Error while making the nginx-prometheus-exporter build file

### ISSUE THREAD

**Issue by litgupta** [nginxinc/nginx-prometheus-exporter#47]
I am trying to install nginx-prometheus-exporter on my system. While applying the "make" command in my $GOPATH/src/github.com/nginxinc/nginx-prometheus-exporter directory, I get an error stating.
>  flag provided but not defined: -mod

What could be the possible error of that? Thank you

**Comment by Rulox** [comment]
Hi @litgupta

In order to help you we are going to need you to provide more information. I suggest you to use the bug report [template](https://github.com/nginxinc/nginx-prometheus-exporter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

If not, could you at least provide the following?

* Go Version (`go version` in your terminal)
* Version of the Prometheus exporter - release version or a specific commit
* Version of Docker/Kubernetes
* The output when you run `make` command. For example :
```
$ make

GO111MODULE=on go test -mod=vendor ./...
ok  	github.com/nginxinc/nginx-prometheus-exporter	(cached)
ok  	github.com/nginxinc/nginx-prometheus-exporter/client	0.017s
?   	github.com/nginxinc/nginx-prometheus-exporter/collector	[no test files]
GO111MODULE=on CGO_ENABLED=0 go build -mod=vendor -installsuffix cgo -ldflags "-X main.version=0.3.0 -X main.gitCommit=ab4e55f" -o nginx-prometheus-exporter
```

Thanks!

**Comment by litgupta** [comment]
Hi @Rulox 
I am new to go environment, I followed the instructions mentioned in README file.


go version -> go1.10.6 linux/amd4
prometheus version -> 2.9.2
I am not using docker/kubernetes, instead, I am using the binary source for local deployment.

The error occurs at the **nginx-prometheus-exporter** tag in Makefile

This is the whole output after attempting **make**
> GO111MODULE=on go test -mod=vendor ./...
> flag provided but not defined: -mod

> Usage of /tmp/go-build441033371/b001/nginx-prometheus-exporter.test:
>   -nginx.plus
>         Start the exporter for NGINX Plus. By default, the exporter is started for NGINX. The default value can be overwritten by NGINX_PLUS environment variable.
>   -nginx.retries uint
>         A number of retries the exporter will make on start to connect to the NGINX stub_status page/NGINX Plus API before exiting with an error. The default value can be overwritten by NGINX_RETRIES environment variable.
>   -nginx.retry-interval value
>         An interval between retries to connect to the NGINX stub_status page/NGINX Plus API on start. The default value can be overwritten by NGINX_RETRY_INTERVAL environment variable. (default 5s)
>   -nginx.scrape-uri string
>         A URI for scraping NGINX or NGINX Plus metrics.
>                 For NGINX, the stub_status page must be available through the URI. For NGINX Plus -- the API. The default value can be overwritten by SCRAPE_URI environment variable. (default "http://127.0.0.1:8080/stub_status")
>   -nginx.ssl-verify
>         Perform SSL certificate verification. The default value can be overwritten by SSL_VERIFY environment variable. (default true)
>   -nginx.timeout value
>         A timeout for scraping metrics from NGINX or NGINX Plus. The default value can be overwritten by TIMEOUT environment variable. (default 5s)
>   -test.bench regexp
>         run only benchmarks matching regexp
>   -test.benchmem
>         print memory allocations for benchmarks
>   -test.benchtime d
>         run each benchmark for duration d (default 1s)
>   -test.blockprofile file
>         write a goroutine blocking profile to file
>   -test.blockprofilerate rate
>         set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
>   -test.count n
>         run tests and benchmarks n times (default 1)
>   -test.coverprofile file
>         write a coverage profile to file
>   -test.cpu list
>         comma-separated list of cpu counts to run each test with
>   -test.cpuprofile file
>         write a cpu profile to file
>   -test.failfast
>         do not start new tests after the first test failure
>   -test.list regexp
>         list tests, examples, and benchmarks matching regexp then exit
>   -test.memprofile file
>         write a memory profile to file
>   -test.memprofilerate rate
>         set memory profiling rate (see runtime.MemProfileRate)
>   -test.mutexprofile string
>         write a mutex contention profile to the named file after execution
>   -test.mutexprofilefraction int
>         if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
>   -test.outputdir dir
>         write profiles to dir
>   -test.parallel n
>         run at most n tests in parallel (default 2)
>   -test.run regexp
>         run only tests and examples matching regexp
>   -test.short
>         run smaller test suite to save time
>   -test.testlogfile file
>         write test action log to file (for use only by cmd/go)
>   -test.timeout d
>         panic test binary after duration d (default 0, timeout disabled)
>   -test.trace file
>         write an execution trace to file
>   -test.v
>         verbose: print additional output
>   -web.listen-address string
>         An address to listen on for web interface and telemetry. The default value can be overwritten by LISTEN_ADDRESS environment variable. (default ":9113")
>   -web.telemetry-path string
>         A path under which to expose metrics. The default value can be overwritten by TELEMETRY_PATH environment variable. (default "/metrics")
> exit status 2
> FAIL    github.com/nginxinc/nginx-prometheus-exporter   0.004s
> make: *** [test] Error 1

**Comment by Rulox** [comment]
Thanks @litgupta 

The exporter uses [Go Modules](https://github.com/golang/go/wiki/Modules). This feature was introduced in Go 1.11. It seems your local Go version does not support this. I suggest you to try one of the following solutions:

* Update your Go to anything greater (or equal) than 1.11. For example, last stable is 1.12.5 

* Build the exporter and run it in a docker container using `make container` This will build an image with the exporter binary inside that you can run with `docker run nginx/nginx-prometheus-exporter:0.3.0` (or whatever name/tag you are using)

Let me know if either of the solutions work for you!

**Comment by litgupta** [comment]
Thanks @Rulox 
Upgrading the go version helped.

**Comment by Rulox** [comment]
Awesome! 

Closing the issue then, feel free to re-open if you encounter any other problem.
