### ISSUE TITLE
Missing link to a grafana dashboard

### ISSUE THREAD

**Issue by marji** [nginxinc/nginx-prometheus-exporter#48]
I've been looking for a grafana dashboard at https://grafana.com/dashboards
but cannot find any which would mentioned compatibility with this exporter. 

Is there any dashboard available? If yes, please mention in the readme.

Thank you very much.

**Comment by Rulox** [comment]
Hi @marji 

Currently we don't have an official Grafana dashboard for this exporter. However, that's something that we are already considering. Please stay tuned. I'll keep this issue open to track the process.

Thanks!

**Comment by dennisotugo** [comment]
I currently have one and I am willing to share! Is there anything that is critical in your mind to have in the graph? @Rulox

**Comment by Rulox** [comment]
Hey @dennisotugo 

Right now we don't have a list of features for the dashboard. The first thing I can think of is that it makes sense to have 2 different grafana dashboards, one for NGINX OSS version and another one for NGINX Plus, as the metrics that you can get from those are different.

As I said, there's no requirements list for this at the moment, so it  would be nice if you share what you have and we can start working around that together. We are always open for community contributions. What do you think?

Thanks!

**Comment by guaychou** [comment]
Hey sir @Rulox , Thanks for your nginx-exporter . Now i need the grafana dashboard , would you like to share with me ? if it's done ? 
Thanks!

**Comment by dennisotugo** [comment]
Hi @Rulox I currently do not use Nginx Plus, so I just shared what I had

**Comment by sijomc** [comment]
I have created a custom Grafana dashboard for nginx-prometheus-exporter. Please see the GitHub URL for customized JSON model of Grafana dashboard. https://raw.githubusercontent.com/sijomc/grafana-dashboard-nginx-prometheus-exporter/master/dashboard.json

**Comment by Rulox** [comment]
Hey @dennisotugo, @sijomc 

Thanks for taking the time to share this! As a result, we now have a clearer view of possible use cases for the Dashboard. 

We are currently doing our own research and soon we will propose a solution based on your input and our research. We would love to hear your feedback when that is done. Please stay tuned!

**Comment by johnjbateman** [comment]
Cant wait to try this dashboard out.

**Comment by Rulox** [comment]
@marji @johnjbateman You can find the official grafana panel for NGINX metrics and its documentation here https://github.com/nginxinc/nginx-prometheus-exporter/tree/master/grafana 

Enjoy! And let us know if there's any issue. Thanks

**Comment by johnjbateman** [comment]
Thanks @Rulox !  One "gotcha" when importing is the Dashboard name cannot be the same as the Folder name.  Once I renamed my dashboard/folder, it worked like a charm!

**Comment by Rulox** [comment]
Thanks @johnjbateman we'll have a look 👍
