### ISSUE TITLE
Support logger injection

### ISSUE THREAD

**Issue by ciarams87** [nginxinc/nginx-prometheus-exporter#484]
As a user of the prometheus exporter as a library
I would like a mechanism to inject a logger
So that I can provide my own logging structure

**Comment by brianehlert** [comment]
Hey @ciarams87
Not a lot of information here about what this entails.
Are there any impacts on core prometheus exporter users?

**Comment by lucacome** [comment]
I think this should be covered with the new changes made in #420

**Comment by kate-osborn** [comment]
> I think this should be possible with the new changes made in #420

@lucacome The logger we use in NGF ([logr.Logger](https://pkg.go.dev/github.com/go-logr/logr#Logger)) does not implement the [log.Logger](https://pkg.go.dev/github.com/go-kit/kit/log) interface so this is still an issue for us.
