### ISSUE TITLE
missing zone_sync states

### ISSUE THREAD

**Issue by Toutzn** [nginxinc/nginx-prometheus-exporter#49]
Hi, 
in your actually version of the exporter, the result of "curl -s 127.0.0.1/api/3/stream/zone_sync" is missing. This is a cluster configuration part in nginx+ which ist activated for sticky learn to sync all cookie in an active/active cluster. Could you please add this values?

e.g. of result:

`
{
  "status": {
    "nodes_online": 1,
    "msgs_in": 316063,
    "msgs_out": 312921,
    "bytes_in": 619285360,
    "bytes_out": 616452834
  },
  "zones": {
    "example_zone_one": {
      "records_total": 153746,
      "records_pending": 11
    },
    "example_zone_two": {
      "records_total": 10940,
      "records_pending": 18
    }
  }
}
`

**Comment by Toutzn** [comment]
Could it bee that all shared zones are missing?

**Comment by pleshakov** [comment]
Hi @Toutzn 

The exporter currently doesn't support the [zone_sync](http://nginx.org/en/docs/http/ngx_http_api_module.html#def_nginx_stream_zone_sync) metrics. We can add those metrics in the future version. Is that what you're asking for?

**Comment by Toutzn** [comment]
Hi @pleshakov ,

yes, right. That will be very nice if you can add this as soon as you can.

**Comment by Toutzn** [comment]
Thanks. Works fine!
