### ISSUE TITLE
Package nginx-prometheus-exporter for distros

### ISSUE THREAD

**Issue by risicle** [nginxinc/nginx-prometheus-exporter#51]
Adding `nginx-prometheus-exporter` to the distro repos at http://nginx.org/packages/ would be useful.

**Comment by pleshakov** [comment]
@risicle 
We don't have any plans to provide packages for the exporter and include them into the  http://nginx.org/packages/  repos.

At the same time, we will continue to publish binaries for the future releases https://github.com/nginxinc/nginx-prometheus-exporter/releases

**Comment by sasah** [comment]
https://github.com/lest/prometheus-rpm/tree/master/nginx_exporter

https://packagecloud.io/prometheus-rpm/release/packages/el/6/nginx_exporter-0.3.0-1.el6.x86_64.rpm
