### ISSUE TITLE
nginx exporter fails to start with Could not create Nginx Client: expected 200 response, got 404

### ISSUE THREAD

**Issue by slaffcheff** [nginxinc/nginx-prometheus-exporter#536]
**Describe the bug**
Exporter fails to start with the following message: Could not create Nginx Client: expected 200 response, got 404

**To reproduce**

Installation:
1. wget https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
2. tar -xvf nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
3. sudo mv nginx-prometheus-exporter /usr/local/bin/
4. sudo vim /etc/systemd/system/nginx-prometheus-exporter.service

```
[Unit]
Description=Nginx Prometheus Exporter
After=network.target

[Service]
User=nginx
ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri=http://127.0.0.1:8080/stub_status
Restart=always

[Install]
WantedBy=multi-user.target

```
5. sudo systemctl daemon-reload
6. sudo systemctl start nginx-prometheus-exporter
7. sudo systemctl enable nginx-prometheus-exporter
8. On status, the service fails to start. 

**Expected behavior**
I expect the service to start and successfully connect to the already running and configured NGINX server.

**Your environment**

- AWS Beanstalk EC2 instance with AL2
- $ nginx -v
nginx version: nginx/1.22.1
- app is also running fine:
$ curl localhost:8080
Backend API is running

I know the recommended guide is using Docker but it shouldn't matter if I manually deploy it in this scenario to the EC2.

**Comment by lucacome** [comment]
Hi @slaffcheff 

can you confirm that you can see the metrics if you go to http://127.0.0.1:8080/stub_status ?

**Comment by Mar1usSo** [comment]
> **Describe the bug** Exporter fails to start with the following message: Could not create Nginx Client: expected 200 response, got 404
> 
> **To reproduce** Steps to reproduce the behavior:
> 
> Installation:
> 
> 1. wget https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
> 2. tar -xvf nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
> 3. sudo mv nginx-prometheus-exporter /usr/local/bin/
> 4. sudo vim /etc/systemd/system/nginx-prometheus-exporter.service
> 
> ```
> [Unit]
> Description=Nginx Prometheus Exporter
> After=network.target
> 
> [Service]
> User=nginx
> ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri=http://127.0.0.1:8080/stub_status
> Restart=always
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 5. sudo systemctl daemon-reload
> 6. sudo systemctl start nginx-prometheus-exporter
> 7. sudo systemctl enable nginx-prometheus-exporter
> 8. On status, the service fails to start.
> 
> **Expected behavior** I expect the service to start and successfully connect to the already running and configured NGINX server.
> 
> **Your environment**
> 
> * AWS Beanstalk EC2 instance with AL2
> * $ nginx -v
>   nginx version: nginx/1.22.1
> * app is also running fine:
>   $ curl localhost:8080
>   Backend API is running
> 
> I know the recommended guide is using Docker but it shouldn't matter if I manually deploy it in this scenario to the EC2.
Confirm your nginx.conf location  is` /stub_status`, for example as below:

server {
    listen   8080;  
    location **/stub_status** {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all; 
    }
}
