### ISSUE TITLE
SCRAPE_URI env does not work anymore

### ISSUE THREAD

**Issue by runningman84** [nginxinc/nginx-prometheus-exporter#585]
**Describe the bug**
In 0.11.x we could use SCRAPE_URI to set the url to some custom path.

**To reproduce**

1. deploy exporter version 1.0
2. View logs '....'
3. See error wp-bedrock-sample-wordpress-bedrock-worker-68b5988df4-rqwqb wordpress-bedrock-nginx 127.0.0.1 - - [21/Dec/2023:11:08:01 +0000] "GET /stub_status HTTP/1.1" 404 11981 "-" "NGINX-Prometheus-Exporter/v1.0.0" "-"

**Expected behavior**
A clear and concise description of what you expected to happen. The old variables should still work or there should be a clear indication the the Readme how to use ENV variables today.

**Your environment**

- Version of the Prometheus exporter - 1.0.0
- Version of Docker/Kubernetes 1.28.x
- [if applicable] Kubernetes platform (e.g. Mini-kube or GCP) EKS
- Using NGINX

**Additional context**
I also tried to use NGINX_SCRAPE_URI but this has also no effect...

**Comment by lucacome** [comment]
Hi @runningman84 

It was removed by mistake. I've opened #586 to fix it
