### ISSUE TITLE
LISTEN_ADDRESS env does not work anymore

### ISSUE THREAD

**Issue by moritzschmitz-oviva** [nginxinc/nginx-prometheus-exporter#602]
**Describe the bug**
Similar to https://github.com/nginxinc/nginx-prometheus-exporter/issues/585 the environment variable has been removed.

**To reproduce**
`docker run -e LISTEN_ADDRESS=":9090" nginx/nginx-prometheus-exporter:1.1.0`

**Expected behavior**
`--web.listen-address` should be possible to set via environment variable.

**Your environment**
Docker version 24.0.7, build afdd53b

**Comment by oseoin** [comment]
Thanks for raising this @moritzschmitz-oviva. These flags are currently referenced from an [external project](https://github.com/prometheus/exporter-toolkit) which I've raised [a pull request](https://github.com/prometheus/exporter-toolkit/pull/195) on. If the PR is not accepted we should still be able to update our implementation to support environment variables.
