### ISSUE TITLE
Problem with connection to Nginx PLUS

### ISSUE THREAD

**Issue by soddevops** [nginxinc/nginx-prometheus-exporter#619]
Nginx [nginx-plus-r22 (1.19.0)] configuration:

`server {
    listen MyIP:9999;

    location /api {
        api write=on;
        # directives limiting access to the API
    }

    location = /dashboard.html {
        root /usr/share/nginx/html;
    }

    # Redirect requests made to the pre-NGINX Plus API dashboard
    location = /status.html {
        return 301 /dashboard.html;
    }

    location = /favicon.ico {
        return 204;
        access_log off;
        log_not_found off;
    }

    location = /basic_status {
        stub_status;
    }

}
`
Run command
./nginx-prometheus-exporter --nginx.plus --nginx.scrape-uri=http://MyIP:9999/api/ --log.level=debug

and check curl:
curl http://127.0.0.1:9113/metrics

response:
`caller=nginx_plus.go:649 level=warn msg="Error getting stats" error="failed to get stats: failed to get endpoints: expected 200 response, got 404. error.status=404; error.text=unknown version; error.code=UnknownVersion; request_id=df67af273247ee1b7d71d89ab092ad67; href=https://nginx.org/en/docs/http/ngx_http_api_module.html"
`

Check api NGINX:
curl http://myIP:9999/api/

Response:
[1,2,3,4,5,6]

When run nginx_exporter without configuration for Plus....

./nginx-prometheus-exporter --nginx.scrape-uri=http://myIP:9999/basic_status --log.level=debug

and check metrics curl http://127.0.0.1:9113/metrics works good.

What 's wrong ?

**Comment by lucacome** [comment]
Hi @soddevops 

at the moment the exporter will try to connect to the latest API version that was available at the time of build. I think https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v0.10.0 should work for you.

We should definitely improve this (it will probably require making some changes to https://github.com/nginxinc/nginx-plus-go-client too)

**Comment by soddevops** [comment]
Aktualnie jestem na urlopie, wracam do pracy 12 lutego.

Do tego czasu ten email może nie zostać przeze mnie przeczytany.

Zgłoszenia serwisowe proszę kierować bezpośrednio na Service Desk lub do Kierownika Zespołu ***@***.***

**Comment by lucacome** [comment]
I opened #629
