### ISSUE TITLE
Grafana dashboard angular deprecation warning

### ISSUE THREAD

**Issue by erfantkerfan** [nginxinc/nginx-prometheus-exporter#677]
**Describe the bug**
error in Grafana: `This panel requires angular. (deprecated)`

**To reproduce**
After importing Grafana dashboard will be shown.

**Expected behavior**
This deprecation warning disapears.

**Your environment**

- Grafana v10.4.1 (d94d597d84)
- latest exporter version
- latest prometheus version
![image](https://github.com/nginxinc/nginx-prometheus-exporter/assets/37825504/fb29f382-1f1d-4308-9c83-111418365b45)

**Comment by Simran-B** [comment]
Same here, running the latest `grafana/grafana-oss` and `prom/prometheus` Docker images shows the deprecation warnings for every panel after importing a dashboard last edited in 2020. What do you need to do to upgrade the panels? Removing the `pluginVersion` attribute from the dashboard JSON didn't help.

**Comment by lucacome** [comment]
Hi @erfantkerfan 

I'm not seeing the deprecation warning, do you still have this problem?

**Comment by Simran-B** [comment]
I'm no longer seeing the deprecation warnings with Grafana 11.1.0 using the same old dashboard.

**Comment by erfantkerfan** [comment]
updated my Grafana to v11.1.0 (5b85c4c2fc) and it's not showing the error anymore.
the problem I saw was in Grafana v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb) if you are willing to check it yourself.
thanks
