### ISSUE TITLE
Random data displayed in Grafana dashboard after import

### ISSUE THREAD

**Issue by hatifnatt** [nginxinc/nginx-prometheus-exporter#69]
After importing dashboard all panels of the dashboard is filled with "Test data: random walk" and Query is "default" not Prometheus as selected during import. Some more details can be found [here](https://github.com/grafana/grafana/issues/18888).

1. Import dashboard with one of the latest version of  Grafana (I'm using 6.4.3)
2. See all panels are filled with random data.

**Expected behavior**
Panels displaying actual data, datasource is correctly set.

**Environment**
* NGINX Prometheus Exporter Version=0.4.2 GitCommit=f017367
* Grafana 6.4.3
* NGINX

**Additional context**
I suppose problem can be fixed  by re-exporting dashboard with Grafana 6.4+. Or by manually adding `"datasource": "${DS_PROMETHEUS}",` into each panel in JSON data, this is how I fixed it for myself.

**Comment by Rulox** [comment]
Hi @hatifnatt 

Thanks for the report! I wasn't able to exactly reproduce this, so in order to really fix the problem could you provide me the following info? Thanks.

* Prometheus version
* Do you have any other data sources in your Grafana instance?
* Do you have any other dashboards?
* Could you let me know exactly the steps you followed? (for example: 1: click on Import Dashboard, 2 paste the JSON and select the Prometheus datasource, 3 click on Import..)

Thanks !

**Comment by hatifnatt** [comment]
- Prometheus version 2.13.1
- Yes I have other data sources
- Yes I have other dashboards

**Steps to reproduce**
- Download dashboard as file from https://raw.githubusercontent.com/nginxinc/nginx-prometheus-exporter/master/grafana/dashboard.json
- Go to Grafana hover '+'  symbol in top left side
- Click on 'Import'
- Click on 'Upload .json file'
- Select file via OS filepicker
- Change name and uid if you already have this dashboard in Grafana
- Select Prometheus source, I have only one Prometheus source named 'Prometheus' so I select it. **But my Prometheus data source is not selected as default.**
![dashboard creation process](https://user-images.githubusercontent.com/807283/67976032-5403c200-fc26-11e9-9113-e8f1dd602b08.png)
- Click 'Import' button
- Resulting dashboard looks like this
![resulting dashboard](https://user-images.githubusercontent.com/807283/67976134-93caa980-fc26-11e9-84f9-41862cdad4b0.png)
- Note for 'Query' (data source) 'default' is selected and for individual `A`, `B` queries `Test data: random walk` is used.
![editing panel](https://user-images.githubusercontent.com/807283/67976256-cd9bb000-fc26-11e9-8712-9318c2e1bf12.png)

I made a test. If I mark 'Prometheus' data source as 'default' in data source parameters dashboard start to work as expected. I think that's why you probably can't reproduce this issue.
![Prometheus is default data source](https://user-images.githubusercontent.com/807283/67976973-3172a880-fc28-11e9-924c-157286eb8370.png)

**Comment by Rulox** [comment]
Ah it makes sense, 

I think it has to do with the default Datasource you are right. We'll have a look at all of this and get back to you soon with the fix.

Thank you so much for the detailed explanation !!

**Comment by saltbo** [comment]
https://github.com/nginxinc/nginx-prometheus-exporter/pull/71/files

replace the json field `"datasource": null` to `"datasource": "${DS_PROMETHEUS}"` worked for me
