### ISSUE TITLE
With Prometheus,i got a metric named "nginx_connections_accepted_total",not "nginx_connections_accepted"

### ISSUE THREAD

**Issue by T-L-T** [nginxinc/nginx-prometheus-exporter#701]
**Describe the bug**
Hello,i am considering is  it a bug?
With Prometheus,i got a metric named "nginx_connections_accepted_total",not "nginx_connections_accepted".
In source code,example dashboard(grafana/dashboard.json),README.md ,it is "nginx_connections_accepted".

**To reproduce**
When i run "curl http://127.0.0.1:9113/metrics",i can get expect result.
~~~
# HELP nginx_connections_accepted Accepted client connections
# TYPE nginx_connections_accepted counter
nginx_connections_accepted 23
# HELP nginx_connections_active Active client connections
# TYPE nginx_connections_active gauge
nginx_connections_active 1
# HELP nginx_connections_handled Handled client connections
# TYPE nginx_connections_handled counter
nginx_connections_handled 23
# HELP nginx_connections_reading Connections where NGINX is reading the request header
# TYPE nginx_connections_reading gauge
nginx_connections_reading 0
# HELP nginx_connections_waiting Idle client connections
# TYPE nginx_connections_waiting gauge
nginx_connections_waiting 0
# HELP nginx_connections_writing Connections where NGINX is writing the response back to the client
~~~
And when i query other metrics,like ``nginx_connections_handled_total`` with PromSQL in Grafana ,i can get the right result.

So i  think i deployed in right way. 

But when i query metric ``nginx_connections_accepted`` with PromSQL in Grafana,i can only  find a  metric named "nginx_connections_accepted_total",instead of "nginx_connections_accepted".

**Expected behavior**

When i query with PromSQL in Grafana,the metric name is "nginx_connections_accepted".

**Your environment**

- nginx-prometheus-exporter v1.1.0
- nginx v1.23.0
- Grafana v10.0.0
- prometheus v2.45.0

**Additional context**
Add any other context about the problem here. Any log files you want to share.

**Comment by lucacome** [comment]
Hi @T-L-T 

Do you have a screenshot? I can't reproduce it, I see `nginx_connections_accepted` in both Graphana and Prometheus.

**Comment by T-L-T** [comment]
> Hi @T-L-T
> 
> Do you have a screenshot? I can't reproduce it, I see `nginx_connections_accepted` in both Graphana and Prometheus.

Thank you for your attention. This is my screenshot.
![WechatIMG499](https://github.com/nginxinc/nginx-prometheus-exporter/assets/35591965/dd9773cd-bd51-4c69-ad65-d0f1818b01c8)

**Comment by T-L-T** [comment]
> Hi @T-L-T
> 
> Do you have a screenshot? I can't reproduce it, I see `nginx_connections_accepted` in both Graphana and Prometheus.

Thank you for your attention again,I think i find the reason for that. The "collector" handle that,like "_total","_sum" and so on.

**Comment by LePau** [comment]
@T-L-T how did you fix it? I am having the same issue.

**Comment by T-L-T** [comment]
> @T-L-T how did you fix it? I am having the same issue.

For me，because of the mimir. Mimir will aggregate the metrics and change the metric name before store them in the prometheus database.
