### ISSUE TITLE
scrape from multiple servers/domains?

### ISSUE THREAD

**Issue by Nurlan199206** [nginxinc/nginx-prometheus-exporter#72]
how to scrape from multiple domains/servers?

i tried args like that

` - "--nginx.scrape-uri=https://domain1.kz/basic_status, https://domain2.kz/basic_status"`

but prometheus showing only one.

**Comment by Nurlan199206** [comment]
ok, i ran two deployments.. seems it's works...


```
nginx_connections_active{instance="172.16.5.164:9113",job="kubernetes-service-endpoints",kubernetes_name="nginx-exporter-service2",kubernetes_namespace="default"} | 7
-- | --
nginx_connections_active{instance="172.16.5.181:9113",job="kubernetes-service-endpoints",kubernetes_name="nginx-exporter-service",kubernetes_namespace="default"} | 188
```

**Comment by Rulox** [comment]
Hi @Nurlan199206 

Yes, it is not possible to add multiple servers on the `scrape-uri` argument, the way you solved the problem is the correct way, 1 exporter per NGINX instance.

Let me know if that's ok and we can close the issue,
Thanks!
