### ISSUE TITLE
Not all HTTP code are exposed

### ISSUE THREAD

**Issue by fabiencharrasse** [nginxinc/nginx-prometheus-exporter#725]
**Describe the bug**
Hello,

i'm trying to fill a grafana dashboard and it seems that only these code are exposed in promhttp_metric_handler_requests_total : 

- 200
- 500
- 503

![image](https://github.com/nginxinc/nginx-prometheus-exporter/assets/86050782/3f091f20-a032-4fce-a223-803aaf5453d2)

I've triggered other code (301/404/etc) in access.log of ngninx but none appear in exporter / prometheus / grafana. Only 200/500/503

**Your environment**

- Version of the Prometheus exporter: 1.2
- Version of Docker: 26.1.3
- Using NGINX

**Comment by lucacome** [comment]
Hi @fabiencharrasse 

`promhttp_metric_handler_requests_total` is the number of times the exporter gathered the metrics from nginx and the response code it received.

I think what you're looking for is `nginxplus_server_zone_responses_codes` (which requires NGINX Plus).

Let me know if that makes sense.

**Comment by fabiencharrasse** [comment]
Thank you for the answer. Too bad, I will do without this functionality.
