### ISSUE TITLE
Latest Docker image is not latest

### ISSUE THREAD

**Issue by t0mmili** [nginxinc/nginx-prometheus-exporter#785]
**Describe the bug**
"latest" Docker image is pointing to version 1.1.2, instead of 1.2.0.

**To reproduce**

1. Execute `docker pull nginx/nginx-prometheus-exporter:latest` in command line.
2. Run container using pulled image.
3. Explore `nginx_exporter_build_info` metric to reveal exporter version.

**Expected behavior**
"latest" Docker image should point to latest version

**Your environment**

- Version of the Prometheus exporter: nginx/nginx-prometheus-exporter:latest

**Comment by lucacome** [comment]
Hi @t0mmili 

Unfortunately we had some issues with the versioning for the last patch release, sorry about that!
We're going to release [1.3.0](https://github.com/nginxinc/nginx-prometheus-exporter/issues/776) soon and this is going to be fixed.

**Comment by lucacome** [comment]
@t0mmili https://github.com/nginxinc/nginx-prometheus-exporter/releases/tag/v1.3.0 was released
