### ISSUE TITLE
Nginx /stub_status instead of /api

### ISSUE THREAD

**Issue by durumanohar** [nginxinc/nginx-prometheus-exporter#8]
Prerequisites
We assume that you have already installed Prometheus and NGINX or NGINX Plus. Additionally, you need to:

Expose the built-in metrics in NGINX/NGINX Plus:
**For NGINX, expose the stub_status page at /stub_status on port 8080.**

Running the Exporter in a Container
To start the exporter we use the docker run command.

To export **NGINX** metrics, run:

$ docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.1.0 -nginx.scrape-uri http://<nginx>:8080**/api**

Shouldn't it be  $ docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.1.0 -nginx.scrape-uri http://<nginx>:8080**/stub_status** ?

**Comment by pleshakov** [comment]
@durumanohar you're right! thank you for reporting. fixed in https://github.com/nginxinc/nginx-prometheus-exporter/pull/9
