### ISSUE TITLE
Support Probing Multiple Nginx Servers

### ISSUE THREAD

**Issue by codyja** [nginxinc/nginx-prometheus-exporter#80]
Would it be possible to mimic how the blackbox exporter behaves and allow probing multiple nginx servers? I'd like to avoid running one nginx-prometheus-exporter per nginx server when we have hundreds of nginx servers. The official blackbox exporter allows you to make an API call to it with the target in the URL. For example:

http://nginx-prometheus-exporter-container:9115/probe?target=nginx-server01.domain.local
http://nginx-prometheus-exporter-container:9115/probe?target=nginx-server02.domain.local

Thanks for the consideration!

**Comment by pleshakov** [comment]
Hi @codyja

Is the main problem running the go exporter on each NGINX server? Would it help if NGINX exposes Prometheus metrics natively?

We already released a [Prometheus exporter for NGINX Plus](https://docs.nginx.com/nginx/admin-guide/dynamic-modules/prometheus-njs/) based on [njs](https://nginx.org/en/docs/njs/). That exporter is like an NGINX module that runs inside NGINX. To expose the metrics, you configure a location inside some virtual server:
```nginx
location = /metrics {
    js_content prometheus_metrics;
}
```

We're thinking about releases an njs Prometheus module for NGINX OSS as well? Do you think such a module can solve your issues?

Thanks

**Comment by schadom** [comment]
I support @codyja idea - or a module for NGINX OSS.

**Comment by codyja** [comment]
@pleshakov a prometheus module for nginx OSS would be even more ideal actually. We run all our nginx instances as containers in nomad with consul. Prometheus has consul service discovery so as soon as the new nginx containers pop up (or move around) we'd begin scraping the /metrics endpoint on them automatically.

**Comment by asrob** [comment]
Hi @pleshakov,

That would be great. Do you have any news about this?

**Comment by 8087** [comment]
Hi @pleshakov ,

That's great. I really hope it will be released.

**Comment by konabharat1** [comment]
Hi @pleshakov : Is there any update on this feature? We are eagerly waiting for this feature to be available on OSS version.

**Comment by appleciderjack** [comment]
Hi @pleshakov : Sounds like a good idea, any idea on when it will come to the OSS version? Thanks
