### ISSUE TITLE
outdated alpine base image

### ISSUE THREAD

**Issue by ingokofler** [nginxinc/nginx-prometheus-exporter#82]
**Describe the bug**
Most recent image on DockerHub (0.5.0, ef5810d4ce30) is based on outdated alpine image with security vulnerabilities.

**To reproduce**
```
$ docker pull nginx/nginx-prometheus-exporter:0.5.0
$ docker run -it --entrypoint=/bin/sh nginx/nginx-prometheus-exporter:0.5.0
$ cat /etc/alpine-release 
3.9.4
$ apk upgrade -s
(1/4) Upgrading musl (1.1.20-r4 -> 1.1.20-r5)
(2/4) Upgrading libcrypto1.1 (1.1.1b-r1 -> 1.1.1d-r2)
(3/4) Upgrading libssl1.1 (1.1.1b-r1 -> 1.1.1d-r2)
(4/4) Upgrading musl-utils (1.1.20-r4 -> 1.1.20-r5)
OK: 6 MiB in 14 packages
```
Base image is from June 2019...

**Expected behavior**
Image should be based on a recent base image that does not contain any security vulnerabilities.

**Your environment**
Docker image 0.5.0 - ef5810d4ce30

**Additional context**
Perhaps one can clarify, if this is intended to be a production grade image or just for development purposes only.

**Comment by Dean-Coakley** [comment]
Hi @ingokofler 

Thanks for reporting this issue.

We will release a new version with an updated alpine base image.

**Comment by ingokofler** [comment]
Hi @Dean-Coakley 

thanks for your quick response. Highly appreciated. I was also suprised that the 9.3 image of Alpine is not really maintained on DockerHub.

And as it seems there are already some others reporting open security issues on Alpine versions but without much influence on the release of new base images.

https://github.com/alpinelinux/docker-alpine/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+CVE
