### ISSUE TITLE
Empty labels with version in nginxexporter_build_info in 0.6.0

### ISSUE THREAD

**Issue by Jasstkn** [nginxinc/nginx-prometheus-exporter#91]
**Describe the bug**
Metric with name nginxexporter_build_info is empty while at 0.4.2 it contains correct info.

**To reproduce**
1. Deploy using 0.6.0 version
2. Check metrics
3. Example output:
```
# HELP nginxexporter_build_info Exporter build information
# TYPE nginxexporter_build_info gauge
nginxexporter_build_info{gitCommit="",version=""} 1
```
**Expected behavior**
Version and commit should appear

**Your environment**
* Version of the Prometheus exporter - 0.6.0
* Version of Docker/Kubernetes: 1.15.11-gke1
* Kubernetes platform: GCP
* NGINX 1.16.1-1

**Comment by Dean-Coakley** [comment]
Hi @Jasstkn 

Thanks for the bug report. We'll get it fixed shortly.

This is a bug with our build pipeline. 
So if the metric is important to you, in the meantime you can build your own image using the Makefile and push an image to your registry.

**Comment by Jasstkn** [comment]
Got it, ty!

**Comment by Dean-Coakley** [comment]
Fixed! 😄
