### ISSUE TITLE
ConstLabels not included in upMetric

### ISSUE THREAD

**Issue by robert-toth** [nginxinc/nginx-prometheus-exporter#95]
**Describe the bug**
Not sure this is a bug or intentionally omitted, but const labels are not attached to the upMetric while it is present on all other metrics.
For the use case of my team we want to show, in Grafana, the number of pods that are up and running and also the version of our build being served by the Nginx in those pods. The number of pods we get by just summing the upMetric but we don't get the version because that is not included in the upMetric

**To reproduce**
1. Run the nginx-prometheus-exporter docker container with CONST_LABELS env. variable set to version=1.2.1
2. Visit the /metrics url to get a list of all the metrics
3. Compare one of the stub_stats metrics with the upMetric and verify that version=1.2.1 is returned by the stub_stats metrics but not the upMetric

**Expected behavior**
I'd like the upMetric to include const labels just lite the stub_stats metrics

**Your environment**
* Version of the Prometheus exporter: 0.6.0 release
* Version of Kubernetes: v1.11.0+d4cacc0
* [if applicable] Kubernetes platform: OpenShift v3.11.135
* Using NGINX

**Additional context**
![image](https://user-images.githubusercontent.com/1016352/79557874-a1280300-80a3-11ea-8bb3-c1b24872a48d.png)

**Comment by Dean-Coakley** [comment]
Hi @robert-toth,

Thanks for including some details on your use case, this case wasn't considered. 
We'll take a look shortly.

Perhaps in the meantime you can set your label directly by configuring it directly in your `prometheus.yaml` instead of using constLabels.
Example: https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-the-sample-targets

The label won't be present in `/metrics` but will be available in Prometheus. Will that work for you?

**Comment by robert-toth** [comment]
Thanks for the quick reply. 
Actually I already "fixed" it in a fork. I can create a pull request, was just not sure if this was intentional or not.

**Comment by robert-toth** [comment]
Verified in my environment with a local build of the fork where I implemented the changes in the PR
![image](https://user-images.githubusercontent.com/1016352/79565750-9aa08800-80b1-11ea-85ba-2268be3affe9.png)

**Comment by robert-toth** [comment]
@Dean-Coakley Thanks for the merge. Will there be a patch release any time soon? Just trying to decide if I should use my locally built docker image for now or wait for a new release.

**Comment by pleshakov** [comment]
Hi @robert-toth 

We will release 0.7.0 during the next two weeks. That will include your bug fix and https://github.com/nginxinc/nginx-prometheus-exporter/pull/86 . Unfortunately, I can't provide any specific date.

**Comment by robert-toth** [comment]
Thanks for the update @pleshakov
